### ISSUE TITLE
Map rendering need an anti-aliasing structure

### ISSUE THREAD

**Issue by 0G4briel** [0G4briel/ReachUp#10]
# We need to vector the rendering map for any scale...

I'm user and using the application, specially, the map and decided zoom-in it the pixels distorces like a photo taked by TekPix

## Steps to reproduce:

1. Debug the app and setup the networking system's [Steps to installation and setup](https://github.com/0G4briel/ReachUp#installation)
2. Run the app on your physical or virtual device
3. At home page, zoom-in map screen

### Scale consider "normal" for general users
![Screenshot_1602023547](https://user-images.githubusercontent.com/59267719/95267066-d6b7d880-080a-11eb-900e-2e93312eac79.png)

### Scale consider "normal" for visual impaired users
![Screenshot_1602023671](https://user-images.githubusercontent.com/59267719/95267155-fa7b1e80-080a-11eb-9d47-1f9eeecbecb3.png)

> For a GUI friendly we need to keep the same quality for any possible scale on our map widget.

**Comment by guilhermedjr** [comment]
With rendering in image form, it will be very complicated.  One possible solution is to increase the pixel density (pixels per inch) of the map image. With canvas rendering (future improvement that is in our plans), we probably wouldn't have this problem.
