### ISSUE TITLE
MapMaker error: cannot read property 'foreach' of undefined

### ISSUE THREAD

**Issue by guilhermedjr** [0G4briel/ReachUp#9]
Error: 
Cannot read property 'foreach' of undefined
at routines.script.js:94
at Array.forEach (<anonymous>)
[...]

Explication: 
When dealing with the other two errors with 'typeof', '.isArray ()', 'Array.From()', etc., we found that: the elements of map.json 'beacons' and 'triBeacons' are, very strangely, being treated as undefined, so they end up not being accessed by forEach loops, which only access arrays. The other elements of json are being treated as expected: like arrays. 
Addendum: the map.json file and the 'jsonmodel' (routines.script.js: 4) are, believe me, valid according to the Java Script Object Notation standards. You can see by yourself here: https://jsonlint.com/

**Comment by guilhermedjr** [comment]
The map.json file as a whole is not undefined, and can be converted to an object (array, more precisely) without problems:

``function` getJson(){
    var object = [];
    try{
      object = JSON.parse(localStorage.getItem("json"));
    }
    catch{
      object = undefined;
      log("undefined!");
    }
    return object;
}

Access errors:

``//draw beacons
  if (typeof mapJson.floors[0].locates != "undefined" && typeof mapJson.floors[0].locates != null){
    mapJson.floors[0].locates.forEach(element => {
      //if (typeof element.beacons != "undefined" && !Array.isArray(element.beacons)){
        element.beacons.forEach(elementBeacon => {
            log(elementBeacon);
            drawBeacons(document.getElementById(elementBeacon.position.x+","+elementBeacon.position.y+""));
        })
      //}
    });
  }

    // draw tri-beacons
    //if (typeof mapJson.floors[0].triBeacons != "undefined" && !Array.isArray(mapJson.floors[0].triBeacons)){
    mapJson.floors[0].triBeacons.forEach(triBeacon => {

        drawTriBeacons(document.getElementById(triBeacon.position.x+","+triBeacon.position.y+""));
    });
  //}

**Comment by 0G4briel** [comment]
Only use the correct array in correct place and be happy!!

**Comment by 0G4briel** [comment]
Just use the correct array in correct place and be happy!!

**Comment by guilhermedjr** [comment]
> Just use the correct array in correct place and be happy!!
😅😅😅
I wanted to kill myself when we discovered the error ....
